// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwS4XgCRZbKdJEfPSPZnikbUpAARbzSLE',
    appId: '1:685702993749:web:04122455789c6b236801dc',
    messagingSenderId: '685702993749',
    projectId: 'robxattendance',
    authDomain: 'robxattendance.firebaseapp.com',
    storageBucket: 'robxattendance.appspot.com',
    measurementId: 'G-W5L9CHVSZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJw5ElvYlsQEN74C8HG_5i706OMyrhyQ',
    appId: '1:685702993749:android:314dad4c08881bc96801dc',
    messagingSenderId: '685702993749',
    projectId: 'robxattendance',
    storageBucket: 'robxattendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhkcquZp0hM9mFk4pyk5KQQ2ZuUSM2J94',
    appId: '1:685702993749:ios:8bb40398a50c506c6801dc',
    messagingSenderId: '685702993749',
    projectId: 'robxattendance',
    storageBucket: 'robxattendance.appspot.com',
    iosBundleId: 'robx.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhkcquZp0hM9mFk4pyk5KQQ2ZuUSM2J94',
    appId: '1:685702993749:ios:8bb40398a50c506c6801dc',
    messagingSenderId: '685702993749',
    projectId: 'robxattendance',
    storageBucket: 'robxattendance.appspot.com',
    iosBundleId: 'robx.attendanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwS4XgCRZbKdJEfPSPZnikbUpAARbzSLE',
    appId: '1:685702993749:web:b7a9c9b6189ae28a6801dc',
    messagingSenderId: '685702993749',
    projectId: 'robxattendance',
    authDomain: 'robxattendance.firebaseapp.com',
    storageBucket: 'robxattendance.appspot.com',
    measurementId: 'G-GZTT4PKGBZ',
  );
}
